### ISSUE TITLE
Memoized port mappings cause issues when a service restarts

### ISSUE THREAD

**Issue by FrelliBB** [palantir/docker-compose-rule#200]
I am using docker-compose-rule in a test but encountered an issue that is giving me some trouble. I have a spring boot service which depends on a mysql database container to be ready first in order to successfully start up. To solve this issue I added a restart policy to my service so my compose file looks something like this (irrelevant lines omitted).

```yml
services:
  database:
    image: myregistry.com/database:latest

  my-service:
    links:
    - database:database.dev
    restart: unless-stopped
```

When the service restarts due to the restart policy the port mapping is changed. This means that the memoizing of portmappings in `com.palantir.docker.compose.connection.Container` will have the wrong port after the service restarts.

Would it be possible to remove this memoizing? Or is there a specific reason for it?
