### ISSUE TITLE
inFormat method on containers do not give correct results when tests are run on docker network

### ISSUE THREAD

**Issue by mdotson** [palantir/docker-compose-rule#209]
Given a docker-compose file that externally connects to the same network as the tests are being run, the `DockerPort#inFormat` method will replace `$HOST` with `localhost` when it should return the container name.

Example: tests are running in a docker container with the network `my-pre-existing-network` with the following `docker-compose.yml`
```
version: "3"
networks:
  default:
    external:
      name: my-pre-existing-network
services:
  db:
    image: postgres
    expose:
    - "5432"
```

When one calls `rule.containers().container("postgres").inFormat("$HOST")`, it returns `localhost` on linux and docker-for-mac when in fact the container is not reachable on `localhost`, but instead at `postgres` since it is on the same network as the tests.
