### ISSUE TITLE
Review uses of "service" and "container" to fit in with our definitions

### ISSUE THREAD

**Issue by joelea** [palantir/docker-compose-rule#28]
We're defining a service as an actual Docker container. A service is then something running inside a container that we can communicate with.

**Comment by fabian-braun** [comment]
Hello,
I'm a new user of this (nice!) library and the naming has caused a little confusion for me.
As a new user I expect the terms "service" and "container" are used according to how they're defined [by docker-compose](https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples).
That is, a service is a "blueprint" to get a concrete container up and running.

When I first did `docker.containers().container(name)` to get a hold of my container I was unsure on what I had to pass as an argument. Consider the following compose-file:
```yml
version: '3'
services:
   service1:
      image: some/image
      command: "echo echo"
      container_name: "container1"
```
Should I pass `container1` or `service1` as name?
I think the api should clearly state that the service name must be passed. Either the parameter name should be changed to `serviceName` or the javadoc should state it.
